version: '3.8'
services:
  familie-db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: familie_admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" # postgres
    networks:
      - familie
    healthcheck:
      test: psql -U familie_admin -d postgres -c 'select 1'
      interval: 5s
      start_period: 30s

  db-init:
    image: postgres:16
    environment:
      PGHOST: familie-db
      PGDATABASE: postgres
      PGUSER: familie_admin
    depends_on:
      familie-db:
        condition: service_healthy
    command:
      - /bin/sh
      - -c
      - |
        psql -c "CREATE USER familie_rbk"
        psql -c "CREATE DATABASE receipebook OWNER familie_rbk"
    networks:
      - familie

networks:
  familie: